{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2e93cc49-16be-4057-bc33-897f33553cb3",
   "metadata": {},
   "outputs": [],
   "source": [
    "import time\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import smtplib\n",
    "from email.mime.multipart import MIMEMultipart\n",
    "from email.mime.text import MIMEText\n",
    "from email.mime.image import MIMEImage\n",
    "from nba_api.stats.static import players\n",
    "from nba_api.stats.endpoints import playercareerstats, playergamelog\n",
    "import os\n",
    "\n",
    "# --- PART 1: DATA SCRAPING & ANALYSIS ---\n",
    "\n",
    "def get_league_top_overperformers(last_n=4, min_mpg=15):\n",
    "    active_players = players.get_active_players()\n",
    "    all_data = []\n",
    "    \n",
    "    print(f\"Scanning {len(active_players)} players...\")\n",
    "    for i, p in enumerate(active_players[:50]): # Limit for testing, remove [:50] for full scan\n",
    "        try:\n",
    "            time.sleep(1.1) # Essential Rate Limiting\n",
    "            p_id, p_name = p['id'], p['full_name']\n",
    "            \n",
    "            # Career Stats\n",
    "            career = playercareerstats.PlayerCareerStats(player_id=p_id).get_data_frames()[0]\n",
    "            if career.empty: continue\n",
    "            c = career.sum()\n",
    "            c_ppg = c['PTS'] / c['GP']\n",
    "            c_ts = (c['PTS'] / (2 * (c['FGA'] + 0.44 * c['FTA']))) * 100 if c['FGA'] > 0 else 0\n",
    "\n",
    "            # Recent Stats\n",
    "            gamelog = playergamelog.PlayerGameLog(player_id=p_id).get_data_frames()[0]\n",
    "            if len(gamelog) < last_n: continue\n",
    "            recent = gamelog.head(last_n)\n",
    "            r_ppg = recent['PTS'].mean()\n",
    "            r_mpg = recent['MIN'].mean()\n",
    "            if r_mpg < min_mpg: continue\n",
    "\n",
    "            r_sum = recent.sum()\n",
    "            r_ts = (r_sum['PTS'] / (2 * (r_sum['FGA'] + 0.44 * r_sum['FTA']))) * 100 if r_sum['FGA'] > 0 else 0\n",
    "\n",
    "            all_data.append({\n",
    "                \"Player\": p_name,\n",
    "                \"Recent PPG\": round(r_ppg, 1),\n",
    "                \"PPG Delta\": round(r_ppg - c_ppg, 1),\n",
    "                \"Recent MPG\": round(r_mpg, 1),\n",
    "                \"Pts/36\": round((r_ppg / r_mpg) * 36, 1),\n",
    "                \"Recent TS%\": round(r_ts, 1),\n",
    "                \"TS% Delta\": round(r_ts - c_ts, 1),\n",
    "                \"EPM\": 0.0, # Placeholder for scraped EPM\n",
    "                \"LEBRON\": 0.0 # Placeholder for scraped LEBRON\n",
    "            })\n",
    "        except: continue\n",
    "\n",
    "    df = pd.DataFrame(all_data)\n",
    "    return df.nlargest(15, 'PPG Delta')\n",
    "\n",
    "# --- PART 2: VISUALIZATION ---\n",
    "\n",
    "def generate_report_graph(df):\n",
    "    fig, axes = plt.subplots(3, 1, figsize=(10, 15))\n",
    "    sns.barplot(x='Player', y='PPG Delta', data=df, ax=axes[0], palette='Reds_r')\n",
    "    axes[0].set_title('Scoring Surge (PPG Delta)')\n",
    "    \n",
    "    sns.barplot(x='Player', y='Recent TS%', data=df, ax=axes[1], palette='Greens_r')\n",
    "    axes[1].set_title('Current Efficiency (True Shooting %)')\n",
    "    \n",
    "    sns.barplot(x='Player', y='Pts/36', data=df, ax=axes[2], palette='Blues_r')\n",
    "    axes[2].set_title('Productivity per 36 Minutes')\n",
    "\n",
    "    for ax in axes:\n",
    "        ax.tick_params(axis='x', rotation=45)\n",
    "    plt.tight_layout()\n",
    "    plt.savefig('nba_daily_report.png')\n",
    "\n",
    "# --- PART 3: EMAIL DELIVERY ---\n",
    "gmail_password = os.environ.get('gmail_password')\n",
    "def send_email(df):\n",
    "    sender = \"jdciesielski1@gmail.com\"\n",
    "    receiver = \"jdciesielski1@gmail.com\"\n",
    "    password = gmail_password\n",
    "\n",
    "    msg = MIMEMultipart()\n",
    "    msg['Subject'] = \"NBA Daily Analysis: Top 15 Overperformers\"\n",
    "    \n",
    "    html = f\"<h3>Top 15 Surging Players</h3>{df.to_html(index=False)}<br><p>See attached graph for details.</p>\"\n",
    "    msg.attach(MIMEText(html, 'html'))\n",
    "\n",
    "    with open('nba_daily_report.png', 'rb') as f:\n",
    "        img = MIMEImage(f.read())\n",
    "        img.add_header('Content-Disposition', 'attachment', filename=\"nba_report.png\")\n",
    "        msg.attach(img)\n",
    "\n",
    "    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:\n",
    "        server.login(sender, password)\n",
    "        server.sendmail(sender, receiver, msg.as_string())\n",
    "\n",
    "# --- EXECUTION ---\n",
    "if __name__ == \"__main__\":\n",
    "    report_df = get_league_top_overperformers()\n",
    "    generate_report_graph(report_df)\n",
    "    send_email(report_df)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
